# Generated by Django 2.0.3 on 2018-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='urgency',
            name='urgency_id',
            field=models.IntegerField(),
        ),
    ]
