# Generated by Django 2.0.3 on 2018-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_auto_20180412_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='urgency',
            name='urgency_id',
            field=models.CharField(max_length=10),
        ),
    ]
