# Generated by Django 2.0.3 on 2018-04-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0006_auto_20180413_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='groups',
        ),
        migrations.AddField(
            model_name='group',
            name='procedures',
            field=models.ManyToManyField(to='webhook.Procedure', verbose_name='list of procedures'),
        ),
    ]
